import { Platform, StyleSheet } from 'react-native';
import type { AppThemeColors } from './palettes';

/** Create / edit task screen — main layout */
export function createTaskMainStyles(c: AppThemeColors) {
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: c.bgCanvas,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingVertical: 10,
      paddingBottom: 12,
      backgroundColor: c.bgCanvas,
    },
    headerIconBtn: {
      width: 44,
      height: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 17,
      fontWeight: '600',
      color: c.textPrimary,
      letterSpacing: -0.2,
    },
    savePill: {
      paddingHorizontal: 18,
      paddingVertical: 9,
      borderRadius: 22,
      backgroundColor: c.accent,
      marginRight: 4,
      shadowColor: c.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.28,
      shadowRadius: 6,
      elevation: 3,
    },
    savePillDisabled: {
      opacity: 0.55,
    },
    savePillText: {
      color: c.onAccent,
      fontSize: 15,
      fontWeight: '600',
    },
    scroll: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 48,
    },
    unifiedSheet: {
      backgroundColor: c.surfaceElevated,
      borderRadius: 20,
      overflow: 'hidden',
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 4,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    sheetSection: {
      paddingHorizontal: 18,
      paddingTop: 20,
      paddingBottom: 18,
    },
    sheetDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.borderMuted,
    },
    sheetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 18,
      gap: 14,
    },
    titleLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: c.textSecondary,
      marginBottom: 8,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    titleHeroInput: {
      fontSize: 23,
      fontWeight: '600',
      color: c.textPrimary,
      paddingVertical: 0,
      letterSpacing: -0.3,
    },
    groupRowLabel: {
      flex: 1,
      fontSize: 16,
      color: c.textPrimary,
      fontWeight: '500',
    },
    groupRowValue: {
      flexShrink: 1,
      fontSize: 15,
      color: c.iconMuted,
      textAlign: 'right',
      marginRight: 4,
    },
    groupRowLabelFlex: {
      fontSize: 16,
      color: c.textPrimary,
      fontWeight: '500',
      minWidth: 72,
    },
    groupRowValueMuted: {
      flex: 1,
      fontSize: 15,
      color: c.textSecondary,
      textAlign: 'right',
      marginRight: 4,
    },
    splitBlock: {
      paddingVertical: 14,
      paddingHorizontal: 18,
    },
    splitSectionTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: c.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 10,
      marginLeft: 38,
    },
    splitRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      minHeight: 50,
      marginLeft: 38,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: c.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderMuted,
    },
    splitLeft: {
      flex: 1.15,
      justifyContent: 'center',
      paddingVertical: 13,
      paddingHorizontal: 14,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: c.borderMuted,
    },
    splitRight: {
      flex: 0.85,
      justifyContent: 'center',
      alignItems: 'flex-end',
      paddingVertical: 13,
      paddingHorizontal: 14,
    },
    splitDateText: {
      fontSize: 15,
      color: c.textPrimary,
      fontWeight: '500',
      lineHeight: 21,
    },
    splitTimeText: {
      fontSize: 18,
      fontWeight: '700',
      color: c.accent,
      letterSpacing: 0.2,
    },
    locationInput: {
      flex: 1,
      fontSize: 16,
      color: c.textPrimary,
      paddingVertical: 0,
      fontWeight: '400',
    },
    colorSection: {
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    colorLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      marginBottom: 12,
    },
    colorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginLeft: 36,
    },
    colorDot: {
      width: 38,
      height: 38,
      borderRadius: 19,
      justifyContent: 'center',
      alignItems: 'center',
    },
    colorDotSelected: {
      borderWidth: 3,
      borderColor: '#ffffff',
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    notesSection: {
      paddingHorizontal: 18,
      paddingTop: 14,
      paddingBottom: 20,
    },
    notesLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      marginBottom: 10,
    },
    notesInput: {
      fontSize: 16,
      color: c.textPrimary,
      minHeight: 100,
      lineHeight: 23,
      marginLeft: 36,
      paddingTop: 0,
      paddingBottom: 4,
    },
  });
}

/** Modals, bottom sheets, iOS picker chrome */
export function createTaskModalStyles(c: AppThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: 'flex-end',
    },
    sheet: {
      backgroundColor: c.modalSheet,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingBottom: Platform.OS === 'ios' ? 34 : 20,
      maxHeight: '60%',
    },
    dateSheet: {
      backgroundColor: c.modalSheet,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    },
    webOnly: {
      fontSize: 15,
      color: c.textSecondary,
      textAlign: 'center',
      marginBottom: 16,
    },
    datePickerScroll: {
      maxHeight: 360,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 24,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: c.border,
    },
    modalActionBtn: {
      paddingVertical: 14,
      paddingHorizontal: 8,
      minWidth: 80,
    },
    modalCancelAction: {
      fontSize: 16,
      fontWeight: '600',
      color: c.danger,
    },
    modalDoneAction: {
      fontSize: 16,
      fontWeight: '600',
      color: c.accent,
      textAlign: 'right',
    },
    handle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.borderMuted,
      alignSelf: 'center',
      marginTop: 12,
      marginBottom: 8,
    },
    title: {
      fontSize: 17,
      fontWeight: '700',
      color: c.textPrimary,
      textAlign: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: c.divider,
    },
    optionText: {
      fontSize: 16,
      color: c.textPrimary,
    },
    selectedText: {
      color: c.accent,
      fontWeight: '600',
    },
    cancelBtn: {
      marginHorizontal: 24,
      marginTop: 12,
      height: 50,
      borderRadius: 14,
      backgroundColor: c.inputBg,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cancelText: {
      fontSize: 16,
      fontWeight: '600',
      color: c.danger,
    },
    iosOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: c.overlayLight,
    },
    iosBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    iosSheet: {
      backgroundColor: c.modalSheet,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      paddingBottom: Platform.OS === 'ios' ? 28 : 16,
    },
    iosToolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.borderMuted,
    },
    iosToolbarCancel: {
      fontSize: 17,
      color: c.textSecondary,
    },
    iosToolbarTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: c.textPrimary,
    },
    iosToolbarDone: {
      fontSize: 17,
      fontWeight: '600',
      color: c.accent,
    },
    iosSpinner: {
      height: 216,
      alignSelf: 'stretch',
    },
  });
}
